### PR TITLE
Updated README with node version

### PR DESCRIPTION
**Pull request by bluefirepatrick**
## Checklist:

- [ ] I have updated the documentation accordingly.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jdempcy** [comment]
## Description

Updated README

## Motivation and Context

Improved documentation

## How Has This Been Tested?

No code change

## Checklist:




- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.

**Comment by jdempcy** [comment]
Hi @ray-lee, I realized this never made it in - this is just a small update to the docs to specify the required node version and have some quickstart style tips for getting it installed. If you think this is overkill we can just close this PR without merging in. Really up to you. This was just a brief update to the documentation that may be helpful, but I am not attached to it getting merged - either way is fine.

**Review by ray-lee — COMMENTED** [review]
This is fine in principle, but I don't want to imply that we require a specific bugfix version of Node 18. I would just say that we require Node 18, and recommend the latest Node 18. That's what we use on CI.

**Review by ray-lee — APPROVED** [review]
I think it's fine to have the installation instructions in there. This looks good to me.

**Pull request merged**
